# Generated by Django 2.2.2 on 2019-09-16 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_OVA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='num_estudiantes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='avance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
