# Generated by Django 2.2.2 on 2019-09-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_OVA', '0002_auto_20190916_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtema',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
