# Generated by Django 2.2.2 on 2019-09-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_OVA', '0003_subtema_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
