# Generated by Django 2.2.2 on 2019-09-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_OVA', '0004_objeto_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.CharField(max_length=200)),
                ('id_Subtema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_OVA.Subtema')),
            ],
        ),
    ]
