# Generated by Django 2.2.2 on 2019-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_OVA', '0005_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='imagen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
