# Generated by Django 2.2.2 on 2019-12-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Código Docente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10, verbose_name='Contraseña')),
                ('username', models.CharField(max_length=10, unique=True, verbose_name='Código Estudiante')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('plan', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
